// react-app/src/App.js
import './App.css';
import { useState } from 'react';

function App() {
  const [items, setItems] = useState([])
  const [input, setInput] = useState("")
  const handleChange = (e) => {
    setInput(e.target.value)
  }
  const handleSubmit = (e) => {
    e.preventDefault()
    setItems([...items, input])
    setInput("")
  }
  return (
    <div className="App">
      <h1>React</h1>
      <input onChange={handleChange}/>
      <button onClick={handleSubmit}>Add</button>
      {
        items.map((item, index) => (
          <div key={index}>
            {item}
          </div>
        ))
      }
    </div>
  );
}

export default App;

// angular-app/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent {
  items:string[] = [];
  item:string = '';

  addItem() {
    this.items.unshift(this.item)
  }
  setItemName(event:any) {
    this.item = event.target.value;
  }
}

<style>
  .center {
    text-align: center;
  }
</style>

<div class="center">
  <h1>Angular</h1>
  
  <input (input)="setItemName($event)"/>
  <button (click)="addItem()">Add Item</button>
  <p *ngFor="let item of items">{{item}}</p>
</div>
